### PR TITLE
add install packages with npm example

### LINKED ISSUE #8: Install Package With npm
An example of installing packages with npm.

### PR DESCRIPTION
**Pull request by joshmanders**
Closes #8

### CODE REVIEW

**Comment by joshmanders** [comment]
@Sequoia & @joepie91 if you guys want to review this, that'd be great.

**Comment by joshmanders** [comment]
Bueller... Bueller... Bueller...

**Comment by Sequoia** [comment]
My main reaction is "this is not an example, it's a blog post/tutorial
about using npm" and therefor both too long and out of scope for examples.

Possibly breaking up into multiples like "installing a dependency",
"installing a global package" but still that's but examples so much as
documentation.

My view is "stick to code examples" BUT this is a great blog post/intro to
using npm 😁

**Comment by joshmanders** [comment]
So should we ditch it?

**Comment by Sequoia** [comment]
Imo yes. Convert to blog post, it's not really an "example".

But it's your project so really your opinion is the one that counts!

**Comment by joshmanders** [comment]
> But it's your project so really your opinion is the one that counts!

No it's OUR project!

**Comment by Sequoia** [comment]
Ha! I guess I'm a silent partner 😋

**Pull request closed without merging**
